spring:
  application:
    name: camel-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/camel_demo
    username: postgres
    password: mou@d2005
    driver-class-name: org.postgresql.Driver
